### ISSUE TITLE
needs https for jquery dependency

### ISSUE THREAD

**Issue by contractor12345678** [tardate/kalinka#1]
Thanks for making this handy site!

I find the calendar picker no longer works for me because of the following http-instead-of-https error:
```Mixed Content: The page at 'https://kalinka.tardate.com/' was loaded over HTTPS, but requested an insecure script 'http://code.jquery.com/jquery-1.4.2.min.js'. This request has been blocked; the content must be served over HTTPS.```

I think it's a simple fix in [this line](https://github.com/tardate/kalinka/blob/master/index.html#L9) of code, but I'd understand if you've moved on / are not interested in a fix.

Thanks again, this was a really handy tool!

**Comment by tardate** [comment]
finally mopping up some old repos/code! ... this is fixed now
